### ISSUE TITLE
Support multiple expansions

### ISSUE THREAD

**Issue by xeno-by** [scalameta/paradise#13]
In `@foo @bar <some definition>` only the leftmost annotation is going to expand. 

This happens because the macro engine needs to remove the currently expanded annotation from the list of annotations on the expandee. Current implementation has no reliable way to determine which annotation is the one, so it nukes everything. 

This should be relatively easy to fix. In the worst case, the typechecker knows about the index of the expanded annotation, so it just needs to communicate it to the expanded.

**Comment by DavidDudson** [comment]
I presume this is the same issue shown in https://gist.github.com/DavidDudson/b2fb2f51c8919a1584911dc5bd5c1d61

On the topic of multiple expansion.

Which order does/should the compiler expand these annotations?

Eg. ``` @foo @bar <some definition> ``` Does foo expand before or after @bar

Another example

```
@Foo
object SomeObject {
  @Bar
  def main(args: Array[String]) = {}
}
```

Does Foo expand before Bar?

**Comment by bar** [comment]
well, it depends if you at handle this @bar or `@bar` :p

**Comment by DavidDudson** [comment]
How many mentions do you get daily? I realised my mistake instantly and switched it, but obviously it was too late haha

**Comment by xeno-by** [comment]
@DavidDudson Hmm, actually it's some different issue. This one is only about putting multiple annotations on a single definition.

I'm currently finishing my PhD dissertation, so it may take a few days for me to look into this. Would you be interested in taking a look at the sources of the plugin and maybe contributing a fix?

Answering your questions:

1) Def macros expand inside out, i.e. macros in enclosing code expand earlier. That's because arguments of def macros are typechecked before the expansion of a def macro takes place, and typechecking causes expansions.

2) Macro annotations expand outside in, i.e. enclosing macros expand earlier. That's because macro annotations are untyped. Annottees of macro annotations may not even make any sense before the enclosing annotations expands, so we can't typecheck them before.

3) In your examples, I would expect `@foo` to expand before `@bar` and `@Foo` to expand before `@Bar`. Otherwise it's a bug.

**Comment by DavidDudson** [comment]
Okay, I'll see what I can do. Need to get my head around the library a little better yet (And no IDE support makes it harder 😦). I might fix both this and the multiple expands problem if I can. I'll create another ticket for the other issue then.
