### ISSUE TITLE
Disappearing val/var modifiers in class parameters

### ISSUE THREAD

**Issue by xeno-by** [scalameta/paradise#136]
Reposted from https://github.com/scalameta/scalameta/issues/555

```
class Identity extends scala.annotation.StaticAnnotation {
  inline def apply(defn: Any): Any = meta {  defn }
}

@Identity
class Test(val value:Int) extends AnyVal
```

Doesn't work, because the `val` modifier is lost and then the `AnyVal` infrastructure complains about that.

**Comment by xeno-by** [comment]
@Keshi thanks a lot for reporting! 

This seems to be an issue in the infrastructure that converts scala.reflect ASTs into scala.meta ASTs (something that we call "the converter").

Here's the relevant code excerpt from https://github.com/scalameta/paradise/blob/1dd67faaf312af15ff8a6ecde963b7a4649108d0/plugin/src/main/scala/org/scalameta/paradise/converters/LogicalTrees.scala#L1130-L1140:

```scala
object PrimaryCtorDef {
  def apply(tree: g.ClassDef): l.PrimaryCtorDef = {
    val CtorDef(mods, name, paramss, stats) = tree.primaryCtor
    val lparamss = paramss match {
      case List(List()) if !tree.mods.hasFlag(CASE) => Nil
      case paramss                                  => paramss
    }
    require(stats.isEmpty)
    PrimaryCtorDef(mods, name, lparamss)
  }
}
```

As you can see, here scala.meta extracts the parameters of the constructor (`paramss`) encoded in scala.reflect parlance and then immediately uses them to build the scala.meta tree corresponding to the primary constructor.

Unfortunately, scala.reflect doesn't have the notion for val/var modifiers on parameters. If the parser finds such a modifier, it drops it and desugars such a parameter into a combination of a constructor parameters and corresponding getters/setters. As a result, `paramss` extracted from the scala.reflect constructor don't know whether they are val/var.

A possible fix would be to change the logic of `PrimaryCtorDef.apply` to:
  1. Check the definition of the input `tree: ClassDef` for whether it has associated getters/setters.
  1. Update `paramss` to include val/var modifiers as appropriate.

I won't have time for this in the coming week or even more, but I would be glad to guide you through contributing a fix. Would you be interested?

**Comment by olafurpg** [comment]
I just submitted #138 to fix this issue.
