### ISSUE TITLE
Make annotations compile-time only

### ISSUE THREAD

**Issue by deterdw** [scalameta/paradise#14]
Would it be possible to make all new-style meta-based macro annotations be compileTimeOnly automatically? Or else, at least to require them all to have that annotation? It seems like a good time to do it now, before "the ship has sailed on this" (as discussed in the comments on http://docs.scala-lang.org/overviews/macros/annotations.html) too.

**Comment by xeno-by** [comment]
That's a very good suggestion. I'll make sure to fix this before a stable release.

**Comment by xeno-by** [comment]
Fixed in https://github.com/scalameta/paradise/commit/b8840b5902052d7194ce48b9a3efa2860079a8e3#diff-4c99817556e14f4c8003b48cf6f40fedR45.
