### ISSUE TITLE
Regression with anon functions as parameters to macro annotations

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/paradise#151]
Using the macro below...

```scala
@compileTimeOnly("@before not expanded")
class before(fun: () => Unit) extends StaticAnnotation {
  inline def apply(defn: Any): Any = meta {
    val q"new $_(() => ${apply: Term.Apply})" = this
    defn
}
```

The below compiles in 3.0.0-M5
but does not in 3.0.0-beta4

Both using scalameta 1.4.0

```scala
@before(() => print("hello"))
def world(): Unit = println(" world")
```

It appears the `() =>` part of the tree has disappeared....

Replacing with:

```scala
@compileTimeOnly("@before not expanded")
class before(fun: () => Unit) extends StaticAnnotation {
  inline def apply(defn: Any): Any = meta {
    val q"new $_(${apply: Term.Apply})" = this // Note this line has changed
    defn
}
```

Successfully compiles.

Surely this is a regression? you should actually have to specify the anon function syntax rather then just having a statement.

**Comment by olafurpg** [comment]
Have you tried running `val q"new $_(() => ${apply: Term.Apply})" = this` through `Syntactic`?

**Comment by DavidDudson** [comment]
@olafurpg That's not the problem (That passes by the way). The problem is how paradise is dealing with parsing the Annotations tree...

the below fails:

`syntactic("""@foo(() => "bar") val bar = ???""")`

```
[info] - @foo(() => "bar") val bar = ??? *** FAILED ***
[info]   scala -> meta converter error
[info]   () => "bar" != "bar"
[info]   parsed tree:
[info]   Defn.Val(Seq(Mod.Annot(Term.Apply(Ctor.Ref.Name("foo"), Seq(Term.Function(Nil, Lit("bar")))))), Seq(Pat.Var.Term(Term.Name("bar"))), None, Term.Name("???"))
[info]   converted tree:
[info]   @foo("bar") val bar = ???
[info]   Defn.Val(Seq(Mod.Annot(Term.Apply(Ctor.Ref.Name("foo"), Seq(Lit("bar"))))), Seq(Pat.Var.Term(Term.Name("bar"))), None, Term.Name("???")) (ConverterSuite.scala:179)

```

**Comment by DavidDudson** [comment]
It should be a trivial fix. I might get onto it myself soon

**Comment by olafurpg** [comment]
My experience is that these things are easiest to fix once you find a minimal unit test for Syntactic!

**Comment by DavidDudson** [comment]
Indeed. I'm busy making an awesome macro based on my PR. So until i release details of that I cant get onto this. Just picked it up when I updated meta for Elysium. So I thought id at least document it.

**Comment by DavidDudson** [comment]
I have to admit that Syntactic suite is going to be a lifesaver later

**Comment by DavidDudson** [comment]
The minimized repro is `syntactic("() => 1")`
I suspect scalac has some funky stuff relating to Function0

**Comment by DavidDudson** [comment]
Future conversation should be in the issue above. This issue will be closed when fixed in scalameta and merged into paradise.
