### ISSUE TITLE
Blocker: Issues with macro annotation expanding quasiquotes pattern matchers

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/paradise#155]
I presume the minimal repro is.

`syntactic("""case q"object $name { ..$stats }"""")`

This completely fails to compile.

`[info]   scalac parse error: illegal start of definition at source-<toolbox>,line-1,offset=0 (ConverterSuite.scala:143)`

## Origin

I'm currently building a very complex `macroAnnotation` macro annotation
https://github.com/DavidDudson/Elysium/blob/master/gen/src/main/scala/nz/daved/elysium/gen/MacroAnnotation.scala

When the following tree is parsed by meta (somewhere) it breaks. https://github.com/DavidDudson/Elysium/blob/master/misc/src/main/scala/nz/daved/elysium/misc/Main.scala

In the first statement of the `macroAnnotation` macro, the 

Heres the debug printout:
```
[error] [Syntax]
[error] ===========================================
[error] object main {
[error]   def apply(obj: Defn.Object): Defn.Object = obj match {
[error]     case q""object "${name}" { .."${stats}" }"" =>
[error]       val main: Stat = q"def main(args: Array[String]): Unit = { ..$stats }"
[error]       q"object $name { $main }"
[error]     case _ =>
[error]       abort("@main does not support this tree")
[error]   }
[error] }
[error] 
[error] [Structure]
[error] ===========================================
[error] Defn.Object(Nil, Term.Name("main"), Template(Nil, Nil, Term.Param(Nil, Name.Anonymous(), None, None), Some(Seq(Defn.Def(Nil, Term.Name("apply"), Nil, Seq(Seq(Term.Param(Nil, Term.Name("obj"), Some(Type.Select(Term.Name("Defn"), Type.Name("Object"))), None))), Some(Type.Select(Term.Name("Defn"), Type.Name("Object"))), Term.Match(Term.Name("obj"), Seq(Case(Pat.Interpolate(Term.Name("q"), Seq(Lit("object "), Lit(" { .."), Lit(" }")), Seq(Pat.Var.Term(Term.Name("name")), Pat.Var.Term(Term.Name("stats")))), None, Term.Block(Seq(Defn.Val(Nil, Seq(Pat.Var.Term(Term.Name("main"))), Some(Type.Name("Stat")), Term.Interpolate(Term.Name("q"), Seq(Lit("def main(args: Array[String]): Unit = { .."), Lit(" }")), Seq(Term.Name("stats")))), Term.Interpolate(Term.Name("q"), Seq(Lit("object "), Lit(" { "), Lit(" }")), Seq(Term.Name("name"), Term.Name("main")))))), Case(Pat.Wildcard(), None, Term.Apply(Term.Name("abort"), Seq(Lit("@main does not support this tree")))))))))))
[error]      
```

I want to fix this as soon as possible. But I have no idea where to start. Any pointers would be appreciated

**Comment by olafurpg** [comment]
What happens if you wrap the case into a match in that call to syntactic?

**Comment by DavidDudson** [comment]
```syntactic("""x match { case q"object $name { ..$stats } }"""")```

```
[info] - x match { case q"object $name { ..$stats } }" *** FAILED ***
[info]   scalac parse error: '=>' expected but eof found. at source-<toolbox>,line-1,offset=45 (ConverterSuite.scala:143)
```

I'm off to sleep now, will check back in the morning

**Comment by olafurpg** [comment]
There's missing an arrow =>

**Comment by DavidDudson** [comment]
Whoops, i realised after i posted. updated that comment

**Comment by olafurpg** [comment]
There's missing a closing double quote.

**Comment by DavidDudson** [comment]
Hmmm. I must have been tired last night. Tests pass with    ` syntactic("""x match { case q"object $name { ..$stats }" => ??? }""")`

So how would it break? Is there something different between the syntactic parser and the regular parser?

This fails....
```
test("Quasiquote expansion succeeds issue #155") {
    @identity
    object foo {
      def apply(obj: Defn.Object): Unit = {
        case q"object $name { ..$stats }" =>
      }
    }
  }
```

**Comment by DavidDudson** [comment]
Okay so have a repro.

Syntactic tests seem to work fine, but it fails in paradise.

Succeeds:
 ``` syntactic("""x match { case q"object $name { ..$stats }" => ??? }""")```


Fails:
```
  test("Quasiquote expansion succeeds issue #155") {
    @identity
    def apply(obj: Defn.Object): Unit = {
      obj match {
        case q"object $name { ..$stats }" =>
      }
    }
  }
```

Heres he before and after toMTree:

```
[info] META 
[info]  ============================
[info] def apply(obj: Defn.Object): Unit = obj match {
[info]   case q""object "${name}" { .."${stats}" }"" => ()
[info] }
[info] G 
[info]  ============================
[info] def apply(obj: Defn.Object): Unit = obj match {
[info]   case StringContext("object ", " { ..", " }").q((name @ _), (stats @ _)) => ()
[info] }
```

I'll keep searching.

**Comment by DavidDudson** [comment]
It seems as if this is possibly a bug in scalameta.

Mtree just calls `toMtrees[Lit]` on `List("object ", " { ..", " }")`

So it could be the case that meta is incorrectly outputting the syntax.

**Comment by DavidDudson** [comment]
I'm wondering whether to leave this open until the fixed scalameta version is used by paradise... Or whether I should just close it

**Comment by olafurpg** [comment]
Keep it open until we bump the meta version in paradise and confirm the bug has been fixed.

**Comment by DavidDudson** [comment]
I'll close this since the meta version has been bumped to 1.6 due to the scalahost work
