### ISSUE TITLE
Access to default parameters of macro annotations 

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/paradise#179]
There is no way to access a default argument from inside the macro annotation: we operate either on a new MyMacro(arg1, ..., argN) in case argument(s) are supplied or on a new MyMacro() otherwise. As far as I understand, we can't inspect annotation definitions themselves, so there should be some 'external' mechanism to do it (?).

Previous issue: https://github.com/scalameta/scalameta/issues/734

**Comment by olafurpg** [comment]
Can you give an example? Default parameters values are defined in the macro annotation, so I don't see exactly what's missing.

**Comment by DavidDudson** [comment]
Closing this as

https://github.com/scalameta/paradise/blob/master/tests/meta/src/test/scala/compile/Expansion.scala#L198

and 

https://github.com/scalameta/paradise/blob/master/tests/meta/src/main/scala/namedParam.scala

Prove it was never an issue to begin with.
