### ISSUE TITLE
Cannot annotate class members if they are part of constructor

### ISSUE THREAD

**Issue by mpollmeier** [scalameta/paradise#192]
Annotating a class member works fine
```
case class Works(i: Int) {
  @foo val s: String = ""
}
```
Unless it is part of the constructor:
```
case class Fails(@foo s: String)
// [error] (usage/compile:compileIncremental) org.scalameta.invariants.InvariantFailedException: invariant failed:
// [error] when verifying stats.forall(((x$1: scala.meta.Stat) => scala.meta.internal.ast.Helpers.XtensionStat(x$1).isBlockStat))
// [error] found that stats.forall(((x$1: scala.meta.Stat) => scala.meta.internal.ast.Helpers.XtensionStat(x$1).isBlockStat)) is false
// [error] where stats = List(val s: String, case class Fails(s: String))

```

Where foo is the identity macro:
```
class foo extends StaticAnnotation {
  inline def apply(defn: Any): Any = meta {
    defn
  }
}
```

This was already discussed [on gitter](https://gitter.im/scalameta/scalameta?at=58237b4be097df75758f2e9f) in November between @taig and @olafurpg, and there is a somewhat dirty workaround. The problem got never reported though, at least I didn't find the issue. 

Here is a repo to reproduce the problem: https://github.com/mpollmeier/scalameta-bug-nested-classmember

**Comment by DavidDudson** [comment]
That is the exact reason why https://github.com/scalameta/paradise/issues/16 exists. Except most of the examples in that ticket are surrounding Defs. This is with class parameters. We seem to be getting more and more examples of why they are still needed.

What's your use case by the way? I'm curious

**Comment by olafurpg** [comment]
Would it be possible to use this workaround?
https://github.com/scalameta/paradise/issues/16#issuecomment-259531690

**Comment by mpollmeier** [comment]
@DavidDudson the use case I have is to replace the marshaller in [gremlin-scala](https://github.com/mpollmeier/gremlin-scala/) which is implemented with old-style macros and [uses an annotation on a class parameter to map the id of a vertex](https://github.com/mpollmeier/gremlin-scala/blob/master/gremlin-scala/src/test/scala/gremlin/scala/MarshallableSpec.scala#L16). 

Annotating the id member with `@id` is a nice solution IMO because I don't want to force the user to name the member e.g. `id`, and the member could be of any type (depending on the underlying graph database used). 

The workaround @olafurpg linked works and is not as dirty as I first thought, so I'm closing this issue. Thank you both!

**Comment by mpollmeier** [comment]
@DavidDudson an even simpler use case would be e.g. in a marshaller/serialiser to annotate certain members with `@nullable`, if you don't want to use `Option` for some reason
