### ISSUE TITLE
paradise 3.0.0-M8 for scala 2.11.11

### ISSUE THREAD

**Issue by drieks** [scalameta/paradise#196]
Hi,

it is possible to  release paradise 3.0.0-M8 for scala 2.11.11?

scala 2.11.10 should not be used, see https://github.com/scala/scala/releases/tag/v2.11.11.

thank you!

**Comment by xeno-by** [comment]
Sure thing! We just need to wait for a Scala.js release, since scala.meta now depends on Scala.js.

**Comment by xeno-by** [comment]
Done
