### ISSUE TITLE
3.0.0-M4 depends on scalameta 1.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by dwijnand** [scalameta/paradise#33]
http://repo1.maven.org/maven2/org/scalamacros/paradise_2.11.8/3.0.0-M4/paradise_2.11.8-3.0.0-M4.pom

**Comment by xeno-by** [comment]
That is an unfortunate oversight, indeed. I'm planning to fix this for 3.0.0-M5.

**Comment by dwijnand** [comment]
Btw, I found out because I was looking at whether https://github.com/scalameta/paradise/issues/10 is still an issue. Perhaps I could spend time on that tomorrow :)
