### ISSUE TITLE
Missing ToMTree converter (Inline modifier)

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/paradise#37]
Short stacktrace

```
org.scalameta.paradise.converters.ConvertException: unsupported tree Apply(TypeTree(), List())
(Apply) scala.meta.internal.inline.inline()
(Template) Template(List(), List(scala.meta.internal.inline.inline()), val _ = _, None)
(Apply) new scala.meta.internal.inline.inline()
(Annotation) Annotation(new scala.meta.internal.inline.inline())
(DefDef) @new scala.meta.internal.inline.inline() def apply(defn: Any): Any = ???
(Template) Template(List(), List(StaticAnnotation()), val _ = _, Some(List(@new scala.meta.internal.inline.inline() def apply(defn: Any): Any = ???)))
(ClassDef) class Before extends StaticAnnotation {
  <paramaccessor> private[this] val fun: _root_.scala.Function0[Unit] = _;
  def <init>(fun: _root_.scala.Function0[Unit]) = {
    super.<init>();
    ()
  };
  @new scala.meta.internal.inline.inline() def apply(defn: Any): Any = ???
}
    at org.scalameta.paradise.converters.ToMtree$toMtree$2$.fail(ToMtree.scala:411)

```

I'm pretty sure this is separate to https://github.com/scalameta/paradise/issues/35

Version: Meta 1.1.0, Paradise 3.0.0-M5

Macro being expanded:
https://github.com/DavidDudson/Elysium/blob/GenExperiments/gen/src/main/scala/nz/daved/elysium/gen/CompileTime.scala

Branch to checkout if you want to experiment (This branch compiling means that the bug is fixed):
https://github.com/DavidDudson/Elysium/tree/GenExperiments

See a full stacktrace in my CI build:
https://travis-ci.org/DavidDudson/Elysium/builds/160046877

**Comment by DavidDudson** [comment]
Note this was probably not expected when first designed. But now meta has a Mod.Inline modifier. So I presume this needs to check the dialect is Paradise211 too

**Comment by Dveim** [comment]
That's related to #35 in sense that converter is not finished at the moment. It lacks ~1/3 of scala-reflect APIs and, most importantly, tests.

I'll fix this one soon.

**Comment by Dveim** [comment]
This one is not as easy as I thought before. Pushed commit with partial fix, however, cannot understand how to fix that
```
error: ';' expected but 'implicit' found.
  inline implicit def foo(a: Int, b: Int): Any = meta {
```
error properly. Error message looks like as if paradise plugin was not included, so I suppose that parsing stage should be modified.

Any ideas and suggestions are welcome.

**Comment by DavidDudson** [comment]
Usually that error comes from inline being seen as an identifier, and not handled in the parser. That was what https://github.com/scalameta/scalameta/pull/475 fixed. Does paradise definitely have these changes? And use the parser in an identical fashion?

**Comment by Dveim** [comment]
Yes, paradise supports `inline` in parsing -- it recognizes keyword first time (so modifiers are updated successfully).

I suppose syntax analyzer should be hijacked in few more places, but could not find where exactly.

**Comment by olafurpg** [comment]
@DavidDudson I'm not sure I quite follow, is this issue about converting code with the `inline` modifier? Have you tried running such a test in `Syntactic`?

**Comment by DavidDudson** [comment]
@olafurpg Yes the issue is about the inline modifier, although the specific case I care about is when inline is used in front of a `def` so that i can generate macro annotations via macro annotations (macro-ception?)

`inline def apply(a: Any): Any = ???`

will get expanded into (`g.Tree`):

`@new scala.meta.internal.inline.inline() def apply(defn: Any): Any = ???`

Which during the g => l => m tree conversion needs to be converted to a modifier `m.Mod.Inline`

Which I believe means adding a `l.Inline()`

which means removing the part of the g.Tree that represents `@new scala.meta.internal.inline.inline()` and adding the inline modifier to the appropriate term which is to the right of it. (Whatever that may be, provided it has modifiers)

Perhaps I am looking at it the wrong way. 

syntactic tests spout the boring regular nonsense that IDE's tell us all the time

`Expecting ; found identifier` or whatever it is *before* the partial fix i have. I need to test with the fix when i get home from work.

The problem i mentioned in gitter is a crash that happens because of unreachable code with a partial fix.

This crash is caused by `l.TermNew` having the case `case g.Select(g.New(tpt), nme.CONSTRUCTOR) =>` which perfectly matches the inline modifier's g.Tree.

Actually looking at it now, I think the TermNew unapply should just return None at this stage.

I'll do some more experiments when i get home from work in a few hours

**Comment by DavidDudson** [comment]
@xeno-by At what point in the conversion from g.Tree => l.Tree should the inline code be swapped? 

The problem I'm having at the moment is that inline isn't "attached" the the def/var/val etc. that it theoretically is connected to. They are processed as 2 separate trees. 

My current thinking is at block level (or anything with stats):

1. Search for the `@new scala.meta.internal.inline.inline()`, 
2. Check that the next stat is a supported thing (var/val/def, I think you mentioned classes possibly in you paper, i cannot remember what the current supported set is)
3. Remove the inline node from the tree
4. Prefix `l.Inline()` as a mod on the corresponding stat

I'll see if this works, but can you please confirm that this is the right approach?

**Comment by DavidDudson** [comment]
@olafurpg it looks like inline isn't supported at all as a keyword in the syntactic tests. Or do you mean i should have the syntactic test as `@new scala.meta.internal.inline.inline() def apply(a: Any): any = ???`

**Comment by DavidDudson** [comment]
@xeno-by Almost complete patch with one issue is ready.

Because toString is called on the final tree https://github.com/scalameta/paradise/blob/master/plugin/src/main/scala/org/scalameta/paradise/typechecker/Expanders.scala#L172

A dialect is required.

This defaults to Scala211:
https://github.com/scalameta/scalameta/blob/master/scalameta/trees/src/main/scala/scala/meta/internal/prettyprinters/TreeToString.scala#L14

Which will complain because inline isnt supported.

My temporary suggestion:

* Allow paradise to modify the origin of Tree's
* Add an origin Origin.Macro which defaults to Paradise211 instead of Scala211.
* the final tree would just call `tree.withOrigin(Origin.Macro).toString`

However, this will not scale very well cross versions and dialects will probably need to be revisited.

**Comment by DavidDudson** [comment]
@olafurpg syntactic tests also fail because the test parser uses dialect.Scala211 not dialect.Paradise211 I'm unsure whether we want to inject dialects into the test parser?

**Comment by olafurpg** [comment]
@DavidDudson I tried to change the parser in `Syntactic` to use the hijacked syntax analyser (which accepts `inline` as a keyword) but with no luck.

Have you tried to change `.toString` to `.syntax(Paradise211)`? `.toString` should be avoided anyways.

**Comment by DavidDudson** [comment]
@olafurpg oh well, we can make that a future issue, non-syntax tests will have to do for now.
Syntax does not support an implicit or explicit Dialect. I guess we could potentially add one

**Comment by olafurpg** [comment]
My bad, I meant `.tokens(Paradise211).mkString`. I think that might work.

**Comment by olafurpg** [comment]
Alternatively, seems you can call `.syntax` on a (Dialect, Tree) pair

```scala
(Paradise211, q"inline def foo = 2").syntax
```

**Comment by DavidDudson** [comment]
One step closer thanks @olafurpg.

The problem now is that the output of `(Paradise211, q"inline def foo = 2").syntax` gets piped into scalac's UnitParser which is not Hijacked. So it has the same problem as the Syntactic tests. We need to pipe the result through the hijacked syntax analyzer.

**Comment by olafurpg** [comment]
The rabbit hole gets deeper : ) 

Have you tried to replace the call to `newUnitParser` with this method here? https://github.com/scalameta/paradise/blob/b7e467b3bb5de06e042ef6bdfa2957ea958dfdd0/plugin/src/main/scala/org/scalameta/paradise/parser/SyntaxAnalyzer.scala#L29

Here's how an instance of the hijacked syntax analyzer can be constructed from a global: https://github.com/scalameta/paradise/blob/b7e467b3bb5de06e042ef6bdfa2957ea958dfdd0/plugin/src/main/scala/org/scalameta/paradise/parser/HijackSyntaxAnalyzer.scala#L19

**Comment by DavidDudson** [comment]
BINGO! Thanks @olafurpg i believe its working!

**Comment by DavidDudson** [comment]
@olafurpg  We may still have a thicker plot :/

Although this toMtree stuff is working (Which technically is this bug). my end goal is not. I'm soo close though.

https://github.com/DavidDudson/Elysium/commit/b375800723d4a705862fbf2a56c343f692c94527

Fails with:

```
[error] <macro>:2: package scala.meta is not a value
[error]   inline def apply(tree: Any): Any = meta {
[error]                                      ^
[error] <macro>:2: implementation restriction: inline methods can only be used to define new-style macro annotations
[error]   inline def apply(tree: Any): Any = meta {
[error]              ^
[error] two errors found
[error] (misc/compile:compileIncremental) Compilation failed
[error] Total time: 8 s, completed 4/01/2017 11:40:10 PM
```

Definitely read the large comment at the top of the file if you are curious as to what the "end goal" is. Note: If anyone actually wants to run this, you need to modify build.sbt to reference a locally published paradise version.

At the moment I'm just trying to hack together a quick and dirty proof that the identity macro actually works.

Anyway. I'm off to sleep, but might ponder this further tomorrow.

**Comment by DavidDudson** [comment]
Ah! I figured it out.

Expanding 
```
@macroAnnotation
object identity {
  def apply(tree: Tree): Tree = tree
}
```

into

```
object identity {
   class identity extends scala.annotation.StaticAnnotation {
     inline def apply(tree: Any): Any = meta {
       tree
     }
   }
}
```

Works.

Expanding....

```
@macroAnnotation
class identity {
  def apply(tree: Tree): Tree = tree
}
```

into

```
class identity extends scala.annotation.StaticAnnotation {
     inline def apply(tree: Any): Any = meta {
       tree
     }
}
```

fails with the above error.

and of course expanding

```
class identity {
  @macroAnnotation
  def apply(tree: Tree): Tree = tree
}
```

Into the same class definition also fails with the above error.

@xeno-by @olafurpg Do you have any ideas why this is? And hopefully a solution. I presume its something to do with macro annotations requiring their parent either being an object or top level (Which of course we don't know when expanding)

The downside of this issue is that I will always have to define my annotations in an object, but they become much more testable as they are plain functions. However I think the patch can be merged without a fix for it. Maybe we could improve the error message in these circumstances? Or abort if trying to expand inline via macro when not in an object?

**Comment by DavidDudson** [comment]
Closed in https://github.com/scalameta/paradise/pull/149
