### ISSUE TITLE
InvariantFailedException?

### ISSUE THREAD

**Issue by DavidDudson** [scalameta/paradise#57]
Probably a programming error... But can we please get a more user friendly error for this case?

``` 
[error] /Users/DavidD/Dropbox/Projects/Elysium/test_test/src/main/scala/nz/daved/elysium/test/StoreTestObject.scala:3: exception during macro expansion:
[error] org.scalameta.invariants.InvariantFailedException: invariant failed:
[error] when verifying pats.forall(((x$14: scala.meta.Pat) => scala.meta.classifiers.`package`.XtensionClassifiable[scala.meta.Pat](x$14)(scala.meta.Tree.classifiable[scala.meta.Pat]).is[Term.Name](Term.this.Name.ClassifierClass[scala.meta.Pat]).`unary_!`))
[error] found that pats.forall(((x$14: scala.meta.Pat) => scala.meta.classifiers.`package`.XtensionClassifiable[scala.meta.Pat](x$14)(scala.meta.Tree.classifiable[scala.meta.Pat]).is[Term.Name](Term.this.Name.ClassifierClass[scala.meta.Pat]).`unary_!`)) is false
[error] where Term = scala.meta.Term$@136c21a6
[error] where pats = List(stateInitial)
[error] 	at org.scalameta.invariants.InvariantFailedException$.raise(Exceptions.scala:15)
[error] 	at scala.meta.Defn$Val$.internal$182(Trees.scala:338)
[error] 	at scala.meta.Defn$Val$.apply(Trees.scala:334)
[error] 	at nz.daved.elysium.test.storeState$inline$.apply(MacroStateStore.scala:29)
[error] @storeState("initial")
[error]  ^
[error] one error found
```

Should be able to reproduce along the lines of...

```Defn.Val(Nil, Term.Name("Foo") :: Nil, None, Lit("Bar"))```

**Comment by DavidDudson** [comment]
For some context, I'm writing a macro that stores the state at expansion time. For testing macro expansions at multiple stages. I believe the code above should "almost" work. I believe the val will actually be a string, but I think thats good enough you compare the structure of it with another for now. https://github.com/DavidDudson/Elysium/commit/22b7c717d94859f748c1201578bf82d859299424

**Comment by xeno-by** [comment]
Thanks for the feedback. That's one of the pain points of the current scala.meta API (https://github.com/xeno-by/scalameta/blob/master/scalameta/trees/src/main/scala/scala/meta/Trees.scala#L169). 

We'll have to revisit some aspects of our AST design in the future. I've been holding that off until the first stable release, but the demand becomes bigger and bigger.

**Comment by DavidDudson** [comment]
Oh I see. https://github.com/xeno-by/scalameta/blob/master/scalameta/trees/src/main/scala/scala/meta/Trees.scala#L206 was what i needed to see.

I thought for some reason that the reason for Pat.Var.Term to differentiate vars from vals. I obviously was wrong, and Var just means "Some variable type". Perhaps its just the error message that need improving. But thats a scala meta issue

**Comment by DavidDudson** [comment]
@olafurpg would you be able to add some info about the pat types and Pat.Var this to the scala workshop Trees section https://olafurpg.github.io/scala.meta-workshop/#Part2:Trees. Might be useful for others
