### ISSUE TITLE
 Compile error on code that it seems should compile

### ISSUE THREAD

**Issue by markehammons** [scalameta/paradise#7]
When I try to compile this sample program using scala meta and the latest macro paradise I get a compilation error that "package scala.meta is not a value"

```
import scala.meta._

/**
	* Created by mhammons on 6/21/16.
	*/
object Test extends App {

	inline def macroThing = meta { q"x < y" }

	val x = 5
	val y = 6

	macroThing
}
```

this is my build.sbt for the file: 
```
scalaVersion := "2.11.8"

addCompilerPlugin("org.scalamacros" % "paradise" % "3.0.0-M3" cross CrossVersion.full)

libraryDependencies += "org.scalameta" %% "scalameta" % "1.0.0"

resolvers += Resolver.sonatypeRepo("releases")
```

Any ideas why I'm hitting this error? It seems like it would be able to compile given the examples for scala meta.

**Comment by xeno-by** [comment]
Current prototype only supports macro annotations. An analogue of def macros will be implemented later.

**Comment by markehammons** [comment]
Ok, thanks a ton.
